id: P001653
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:12:32.979638
source_metadata:
  id: bdr:W1KG21753
  title: པདྨ་འོད་འབར་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    858989d0c5b84d999e9293cd76d31660:
      image_group_id: I1KG21835
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
